#!/usr/bin/env python3
"""Regenerate Sources/KSTCore/BlocklistSeed.swift from a KST2Me install.

KST2Me ships BadSpotters.txt and BadNames.txt alongside the .exe. They are
Bo OZ2M's curation and there is no feed for them — the only way to refresh
is to unpack a newer KST2Me and re-run this:

    ./tools/import-kst2me-lists.py \
        "~/Library/Mobile Documents/com~apple~CloudDocs/Documents/Ham/KST2Me"

That directory is the shack's kept copy of the KST2Me distribution, with a
WHAT-THIS-IS.txt next to the files explaining what each one is for. It was
in iCloud Downloads/ until 2026-09-08; do not point this back at a
Downloads folder, they get tidied away.

Two things about the source files are not guessable and are why this script
exists rather than a one-line shell pipeline: BadNames.txt is ISO-8859-1,
not UTF-8, and its entries are whitespace-significant substring patterns
rather than whole names. See docs/PROTOCOL.md.
"""
import io, os, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "."
HERE = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(HERE, "..", "Sources", "KSTCore", "BlocklistSeed.swift")


def read(name, enc):
    with open(os.path.join(SRC, name), encoding=enc) as f:
        return [line.rstrip("\r\n") for line in f]


def dedupe(items, key=lambda x: x):
    seen, out = set(), []
    for i in items:
        k = key(i)
        if k not in seen:
            seen.add(k)
            out.append(i)
    return out


def lit(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


spotters = dedupe(l.strip().upper() for l in read("BadSpotters.txt", "utf-8") if l.strip())

# Whitespace is significant — "@ home" and "SM/ " are patterns, not words —
# so only the line ending is stripped. Entries under three characters are
# dropped: the file's tail is fragments like "CA", "G0" and ":" that would
# match inside almost any name.
names = dedupe((l for l in read("BadNames.txt", "iso-8859-1") if len(l) >= 3),
               key=str.lower)
names.sort(key=lambda s: (-len(s), s.lower()))

out = io.StringIO()
out.write('''// Generated by tools/import-kst2me-lists.py — do not hand-edit.
//
// Source: Bo OZ2M's KST2Me distribution (BadSpotters.txt, BadNames.txt).
// These lists are his curation, built up over years of running the ON4KST
// VHF rooms, and are used here with credit. There is no feed for them —
// re-run the importer against a newer KST2Me to refresh.
//
// Kept verbatim apart from line-ending stripping, de-duplication, and
// dropping BadNames entries under three characters.

extension Blocklist {

    /// Callsigns KST2Me suppresses in DX spots — busted calls, malformed
    /// portable prefixes, and known-bogus spotters.
    ///
    /// Fifty-two of the seventy shipped entries are exactly seven
    /// characters, which is KST2Me's own storage width rather than a real
    /// callsign length: `EI/GI0U` is a truncation of `EI/GI0UHV`, and the
    /// file contains both. `Blocklist.blocks(spotter:)` compensates; the
    /// data here stays as shipped.
    public static let seedSpotters: [String] = [
''')
for s in spotters:
    out.write("        %s,\n" % lit(s))

out.write('''    ]

    /// Substring patterns KST2Me strips out of the ON4KST name field.
    ///
    /// **Not** a list of whole bad names. Entries are fragments, and their
    /// leading and trailing spaces are part of the pattern (`"@ home"`,
    /// `"SM/ "`); `"Lking"` is a fragment of "Looking". Sorted longest
    /// first so the most specific pattern applies before its substrings.
    ///
    /// The short end of the list is ordinary English words — `"only"`,
    /// `"with"`, `"Very"`, `"Seal"`, `"test"` — which is why
    /// `Blocklist.Tier` exists and why the default tier stops short of
    /// them.
    public static let seedNameFragments: [String] = [
''')
for n in names:
    out.write("        %s,\n" % lit(n))

out.write("    ]\n}\n")

with open(DEST, "w") as f:
    f.write(out.getvalue())

print("wrote %s" % os.path.normpath(DEST))
print("  spotters:       %d" % len(spotters))
print("  name fragments: %d" % len(names))
